### ISSUE TITLE
Cleanup `[tool.pytest.ini_options]`

### ISSUE THREAD

**Issue by dhirschfeld** [energy-quants/eq-example#21]
e.g.
```toml
[tool.pytest.ini_options]
# https://docs.pytest.org/en/7.1.x/reference/reference.html#ini-options-ref
minversion = "7.3"
testpaths = ["tests"]
addopts = [
  "-lv",
  "--ignore=tests/debug.py",
  "--tb=short",
  "--color=yes",
  "--code-highlight=yes",
  "--import-mode=importlib",
  "--doctest-modules",
  "--doctest-continue-on-failure",
]
junit_family = "xunit2"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
```
